### ISSUE TITLE
Plugin doesn't  work in Godot 3.1

### ISSUE THREAD

**Issue by chadalen** [scayze/MagicaVoxel-Importer#10]
Plugin doesn't work in Godot 3.1

https://i.imgur.com/tAZtxFS.gif

**Comment by JohnCWakley** [comment]
Just confirming for Godot 3.1-stable, the plugin does not work.

**Comment by scayze** [comment]
Hey y'all! I have patched it for 3.1, you have to download the update manually here from github though, it takes a while to get the update approved on the assetstore :)
sorry for taking so long

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
nice thank you 👍
