### ISSUE TITLE
Support Goxel ".gox" File Format

### ISSUE THREAD

**Issue by qbradq** [scayze/MagicaVoxel-Importer#11]
I would like to add support for the [Goxel](https://github.com/guillaumechereau/goxel) ".gox" file format. I prefer using Goxel because it is a native Linux application, and because I like that the source code is still on github :smile: Would you accept a PR to add this support? Or would you prefer I fork the plugin?

[File format reference](https://github.com/guillaumechereau/goxel/blob/master/src/formats/gox.c)

Thank you

**Comment by scayze** [comment]
I already thought about supporting multiple voxel formats, it would certainly be handy! 

A PR would be amazing! Of course I would accept it :D

I'm glad people are interested in this project :)

**Comment by qbradq** [comment]
After looking at the .gox file format and the source code of Goxel itself I'm giving up on this. The voxel layer data is compressed in such a way that it would be impractical to implement an importer in gdscript. Specifically Goxel uses zlib compression within voxel layers. I am just going to use MagicaVoxel :)
