### ISSUE TITLE
No mesh in Godot file explorer

### ISSUE THREAD

**Issue by neonmoe** [scayze/MagicaVoxel-Importer#3]
Installed this plugin, saved my .vox file in a folder called Models, but the folder seems empty in Godot. When I check with my file explorer, the .vox file is still there, but in Godot, no vox or mesh.

I'm running Godot v3.0.2, has the plugin broken in the latest version?

**Comment by scayze** [comment]
Hm. Weird. it works fine for me.
Could you check the console output for any errors?

**Comment by neonmoe** [comment]
I created a new project, imported the addon, and saved a .vox file inside the project folder. Here's all of the output:
![image](https://user-images.githubusercontent.com/22432472/38884940-e1f631fa-4279-11e8-9b7b-efb6a66e83a4.png)

And here's the contents of the project folder:
![image](https://user-images.githubusercontent.com/22432472/38884966-faa33162-4279-11e8-83d7-bbf056bbb2af.png)

**Comment by scayze** [comment]
According to the first line of your output you are running a custom version or atleast a manually compiled version of godot. could you try and download the official one and test if the error persists?

**Comment by neonmoe** [comment]
Downloaded the official one and re-made the project as previously described. Output looks the same and the file structure is the same.
![image](https://user-images.githubusercontent.com/22432472/38899837-eb5d97ba-42a1-11e8-9703-68e2eb0bf97e.png)

It's kind of concerning that *nothing* appears in the Godot file browser. Am I missing a step, isn't the importing an automatic process? Here's my Godot FileSystem tab:
![image](https://user-images.githubusercontent.com/22432472/38899917-291f98aa-42a2-11e8-8737-78b947f82ada.png)

**Comment by scayze** [comment]
Might be a stupid question, but are you sure you enabled the plugin in the project settings?

**Comment by neonmoe** [comment]
Oh. It was that yes, didn't realize you needed to do that manually. Sorry for wasting your time, and thanks for helping!
