### ISSUE TITLE
Shouldn't there be a .mesh file?

### ISSUE THREAD

**Issue by ellogwen** [scayze/MagicaVoxel-Importer#5]
I installed the plugin and activated it in the project settings. It worked as intended (thank you for that by the way, now I can finally, directly export from VoxelShop to godot <3 ... via magicavoxel file format (edit: found out how to import from voxelshop via collada directly as well).

According to the description, there should be a .mesh file created. I do not see such a mesh file, but the MeshInstance is created and the texture (SpatialMaterial) is set correctly. Where do I find the .mesh and texture now on disk, or is it embedded somewhere?

**Comment by ellogwen** [comment]
I found one in a hidden .import folder 
(Test-MagicaVox.vox-88cf31d63f382542c86deb530f2173ec.mesh)
I thought there would be one created in the folder the .vox file is in, but ok, found the mesh, issue closed ^^

**Comment by scayze** [comment]
Oh, the text is outdated, gotta update that. The mesh file is not visible to the user anymore, instead its accessible directly through the .vox file in the filemanager. But yeah, you are still able to find it as .import file. Is there any specific reason that you need the .mesh file itself?

**Comment by ellogwen** [comment]
no, was just wondering, because the description said so. Maybe just scared that something went wrong and could be troublesome at a later point
