### ISSUE TITLE
method to_rgb is not declared

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [scayze/MagicaVoxel-Importer#9]
to_rgb no longer exists in newer Godot. I don't quite know how to fix this.

![capture](https://user-images.githubusercontent.com/36826319/50506824-9f6aa400-0a48-11e9-8fb5-f3f9c3395c37.PNG)

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I assume the fix is Color(voxColors[d.color]-1)

**Comment by scayze** [comment]
this is now fixed, sorry for taking so long
